-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.argo_embeddings (
  id bigint NOT NULL DEFAULT nextval('argo_embeddings_id_seq'::regclass),
  float_id text NOT NULL,
  cycle_number integer NOT NULL,
  summary text,
  embedding USER-DEFINED,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT argo_embeddings_pkey PRIMARY KEY (id),
  CONSTRAINT argo_embeddings_float_id_cycle_number_fkey FOREIGN KEY (float_id) REFERENCES public.argo_metadata(float_id),
  CONSTRAINT argo_embeddings_float_id_cycle_number_fkey FOREIGN KEY (float_id) REFERENCES public.argo_metadata(cycle_number),
  CONSTRAINT argo_embeddings_float_id_cycle_number_fkey FOREIGN KEY (cycle_number) REFERENCES public.argo_metadata(float_id),
  CONSTRAINT argo_embeddings_float_id_cycle_number_fkey FOREIGN KEY (cycle_number) REFERENCES public.argo_metadata(cycle_number)
);
CREATE TABLE public.argo_metadata (
  float_id text NOT NULL,
  cycle_number integer NOT NULL,
  file_id uuid,
  platform_number text NOT NULL,
  platform_type text,
  pi_name text,
  juld timestamp with time zone,
  juld_qc text,
  latitude double precision,
  longitude double precision,
  geom USER-DEFINED,
  direction text,
  data_mode text,
  has_adjusted boolean DEFAULT false,
  position_qc text,
  positioning_system text,
  positioning_system_2 text,
  position_accuracy_1 double precision,
  position_accuracy_2 double precision,
  profile_pres_qc text,
  profile_temp_qc text,
  profile_psal_qc text,
  vertical_sampling_scheme text,
  config_mission_number integer,
  min_pres double precision,
  max_pres double precision,
  mean_pres double precision,
  min_temp double precision,
  max_temp double precision,
  mean_temp double precision,
  min_psal double precision,
  max_psal double precision,
  mean_psal double precision,
  ocean_region text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT argo_metadata_pkey PRIMARY KEY (float_id, cycle_number),
  CONSTRAINT argo_metadata_file_id_fkey FOREIGN KEY (file_id) REFERENCES public.file_info(file_id)
);
CREATE TABLE public.argo_trajectory (
  id bigint NOT NULL DEFAULT nextval('argo_trajectory_id_seq'::regclass),
  float_id text NOT NULL,
  cycle_number integer,
  ts timestamp with time zone NOT NULL,
  latitude double precision,
  longitude double precision,
  geom USER-DEFINED,
  position_qc text,
  positioning_system text,
  position_error_reported double precision,
  position_error_estimated double precision,
  parking_pressure double precision,
  surface_pressure double precision,
  measurement_code integer,
  file_id uuid NOT NULL,
  CONSTRAINT argo_trajectory_pkey PRIMARY KEY (id),
  CONSTRAINT argo_trajectory_file_id_fkey FOREIGN KEY (file_id) REFERENCES public.file_info(file_id)
);
CREATE TABLE public.calibration_info (
  id bigint NOT NULL DEFAULT nextval('calibration_info_id_seq'::regclass),
  float_id text NOT NULL,
  cycle_number integer NOT NULL,
  parameter text NOT NULL,
  parameter_sensor text,
  calib_equation text,
  calib_coefficients jsonb,
  calib_comment text,
  calib_date timestamp with time zone,
  file_id uuid,
  CONSTRAINT calibration_info_pkey PRIMARY KEY (id),
  CONSTRAINT calibration_info_file_id_fkey FOREIGN KEY (file_id) REFERENCES public.file_info(file_id),
  CONSTRAINT calibration_info_float_id_cycle_number_fkey FOREIGN KEY (float_id) REFERENCES public.argo_metadata(float_id),
  CONSTRAINT calibration_info_float_id_cycle_number_fkey FOREIGN KEY (float_id) REFERENCES public.argo_metadata(cycle_number),
  CONSTRAINT calibration_info_float_id_cycle_number_fkey FOREIGN KEY (cycle_number) REFERENCES public.argo_metadata(float_id),
  CONSTRAINT calibration_info_float_id_cycle_number_fkey FOREIGN KEY (cycle_number) REFERENCES public.argo_metadata(cycle_number)
);
CREATE TABLE public.file_info (
  file_id uuid NOT NULL DEFAULT gen_random_uuid(),
  file_name text NOT NULL,
  data_type text,
  format_version text,
  handbook_version text,
  reference_date_time timestamp with time zone,
  data_mode text,
  data_state_indicator text,
  project_name text DEFAULT 'Argo'::text,
  dc_reference text,
  date_creation timestamp with time zone,
  date_update timestamp with time zone,
  data_centre text,
  notes text,
  float_count integer,
  profile_count integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT file_info_pkey PRIMARY KEY (file_id)
);
CREATE TABLE public.history_info (
  id bigint NOT NULL DEFAULT nextval('history_info_id_seq'::regclass),
  float_id text NOT NULL,
  cycle_number integer NOT NULL,
  history_institution text,
  history_step text,
  history_software text,
  history_software_release text,
  history_reference text,
  history_date timestamp with time zone,
  history_action text,
  history_parameter text,
  history_start_pres double precision,
  history_stop_pres double precision,
  history_previous_value text,
  history_qctest text,
  file_id uuid,
  CONSTRAINT history_info_pkey PRIMARY KEY (id),
  CONSTRAINT history_info_file_id_fkey FOREIGN KEY (file_id) REFERENCES public.file_info(file_id),
  CONSTRAINT history_info_float_id_cycle_number_fkey FOREIGN KEY (float_id) REFERENCES public.argo_metadata(float_id),
  CONSTRAINT history_info_float_id_cycle_number_fkey FOREIGN KEY (float_id) REFERENCES public.argo_metadata(cycle_number),
  CONSTRAINT history_info_float_id_cycle_number_fkey FOREIGN KEY (cycle_number) REFERENCES public.argo_metadata(float_id),
  CONSTRAINT history_info_float_id_cycle_number_fkey FOREIGN KEY (cycle_number) REFERENCES public.argo_metadata(cycle_number)
);
CREATE TABLE public.profile_parquet_index (
  id bigint NOT NULL DEFAULT nextval('profile_parquet_index_id_seq'::regclass),
  float_id text NOT NULL,
  cycle_number integer NOT NULL,
  parquet_uri text NOT NULL,
  row_count bigint,
  max_depth double precision,
  min_pres double precision,
  max_pres double precision,
  variables jsonb,
  file_size_bytes bigint,
  created_at timestamp with time zone DEFAULT now(),
  storage_status text DEFAULT 'uploaded'::text,
  CONSTRAINT profile_parquet_index_pkey PRIMARY KEY (id),
  CONSTRAINT profile_parquet_index_float_cycle_fk FOREIGN KEY (float_id) REFERENCES public.argo_metadata(float_id),
  CONSTRAINT profile_parquet_index_float_cycle_fk FOREIGN KEY (float_id) REFERENCES public.argo_metadata(cycle_number),
  CONSTRAINT profile_parquet_index_float_cycle_fk FOREIGN KEY (cycle_number) REFERENCES public.argo_metadata(float_id),
  CONSTRAINT profile_parquet_index_float_cycle_fk FOREIGN KEY (cycle_number) REFERENCES public.argo_metadata(cycle_number)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text,
  full_name text,
  avatar_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.spatial_ref_sys (
  srid integer NOT NULL CHECK (srid > 0 AND srid <= 998999),
  auth_name character varying,
  auth_srid integer,
  srtext character varying,
  proj4text character varying,
  CONSTRAINT spatial_ref_sys_pkey PRIMARY KEY (srid)
);